# languages to include in i19dict.js (no separate loading)
LANGUAGES_INCLUDE=en
# other languages to generate
LANGUAGES_OTHER=de
# translation domain
DOMAIN=test
# locale directory
LOCALES=locale/
# HTML sources
HTML=*.html
# OUTPUT
I19JS=i19dict.js


include $(shell i19conf common.mk)
