# call: make -I../i19py

# languages to include in i19dict.js (no separate loading)
LANGUAGES_INCLUDE=en
# other languages to generate
LANGUAGES_OTHER=de
# translation domain
DOMAIN=demo
# locale directory
LOCALES=locale/
# HTML sources
HTML=*.html
# OUTPUT
I19JS=i19dict.js


include common.mk
